### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [roboflow/notebooks#103]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

This issue affects the entire repo, not any single notebook.

### Bug

Looks like the `CONTRIBUTING` file references a `LICENSE.md` file in another repo:

https://github.com/roboflow/notebooks/blob/acfb02a32d157581cb1163d355f4ff59d3849832/CONTRIBUTING.md#L19-L21

but it would be helpful if this repo were self-contained and included its own license file, which would also let GitHub add a license badge to the repo to clearly specify the license.

### Environment

N/A

### Minimal Reproducible Example

N/A

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by yeldarby** [comment]
While we’d like to add a license, it’s difficult to do so because there’s an argument to be made that some of these notebooks could be considered derivative works of the repos they demonstrate how to use (and thus should have inherit their licenses from those) and each of those have their own different licenses.

**Comment by SkalskiP** [comment]
@yeldarby, how about adding LICENSE to our repo with a disclaimer that it only covers our code, not code in libraries we showcase?
