### ISSUE TITLE
YoloX

### ISSUE THREAD

**Issue by SalKly** [roboflow/notebooks#106]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

how-to-track-and-count-vehicles-with-yolov8.ipynb
https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-and-count-vehicles-with-yolov8.ipynb#scrollTo=8KdBkOflo2xY&uniqifier=1

### Bug

In the installation  of ByteTrack Step it shows the following error :
![Colab](https://user-images.githubusercontent.com/101665758/235332096-6fa0ec18-cee8-47c8-901c-eff66d4c9425.png)
"

### Environment

-Google colab

### Minimal Reproducible Example

%cd {HOME}/ByteTrack
import yolox

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mo-traor3-ai** [comment]
Hi @SalKly - as a note, [this tutorial is specifically for YOLOv8](https://blog.roboflow.com/yolov8-tracking-and-counting/), which is not the same model as YOLOX.
* https://roboflow.com/model/yolov8
* https://roboflow.com/model/yolox
![IMG_8374](https://user-images.githubusercontent.com/89935638/235371009-a6351ecf-18bd-42fa-aaa2-2a7a3d891f85.jpeg)

There is a [YOLOv8x model](https://github.com/ultralytics/ultralytics), if that is what you were looking for? It is just the larger size YOLOv8 model.
![IMG_8373](https://user-images.githubusercontent.com/89935638/235370970-f55a949a-15cf-4e4c-a523-75bcd4a6a768.jpeg)

To try this with YOLOX, first ensure you’ve installed YOLOX to the environment, with the necessary dependencies. I haven’t tested this notebook with YOLOX, since it is a YOLOv8 notebook, so I’m not sure how well it will work with ByteTrack. You may need to make some customizations.

**Comment by Jkfyr** [comment]
Yes, but ByteTrack uses Yolox si it is a problem with the instalation of Bytetrack

**Comment by AT9991** [comment]
I am having the same issue, this appears when installing bytetrack

**Comment by SkalskiP** [comment]
Hi, @SalKly, @Jkfyr and @AT9991 👋🏻! I spent some time yesterday and fixed the `how-to-track-and-count-vehicles-with-yolov8.ipynb` notebook again. I'm closing the issue. However, feel free to reopen it if you face any more issues.

**Comment by vhuard** [comment]
i have the same issue today as well
how did you fix it?

**Comment by vhuard** [comment]
with error code 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-7-db369db504f9>](https://localhost:8080/#) in <cell line: 23>()
     21 
     22 
---> 23 import yolox
     24 print("yolox.__version__:", yolox.__version__)

2 frames
[/content/ByteTrack/yolox/utils/model_utils.py](https://localhost:8080/#) in <module>
      5 import torch
      6 import torch.nn as nn
----> 7 from thop import profile
      8 
      9 from copy import deepcopy

ModuleNotFoundError: No module named 'thop'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by SkalskiP** [comment]
Hi @vhuard 👋🏻 ! I just released a new version of the notebook, that should fix that problem. Let me know if you will still experience any issues.

**Comment by vhuard** [comment]
Hello Piotr
I just commit an issue on roboflow.
I was generating a version of dataset and the app launch the
demo.roboflow.com saying it cannot load the model and I am stuck not even
possible to reopen properly the dataset to export the data.
Can you help me?

Vincent

Le lun. 19 juin 2023 à 06:17, Piotr Skalski ***@***.***> a
écrit :
