### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by aamirali13** [roboflow/notebooks#307]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

[Track and Count Vehicles with YOLOv8 + ByteTRACK + Supervision](https://github.com/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-and-count-vehicles-with-yolov8.ipynb)

### Bug

I was trying to run the notebook by using my own weights but getting the mentioned error throughout. It's not working for even the weights which are shared with link.

### Environment

Google colab

### Minimal Reproducible Example

!python detect.py --weights content/best.pt --img 1280 --conf 0.25 --source content/08fd33_4.mp4 --name custom

or

model = torch.hub.load('ultralytics/yolov5', 'custom', WEIGHTS_PATH, device=0,force_reload=True)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
Hi @aamirali13 👋 

The notebook you mentioned uses Yolov8, whereas the code you pasted mentions yolov5. These two models are incompatible - maybe that's related to your issue?

**Comment by aamirali13** [comment]
Sorry for the misunderstanding.
Notebook : [Football Players Tracking with YOLOv5 + ByteTRACK](https://github.com/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-football-players.ipynb)

This is what I am trying to run and getting issue.

**Comment by LinasKo** [comment]
Hi @aamirali13, unfortunately, figuring out the issue is taking more time than I have to spare.

Instead, I'd like to offer an alternative.  Instead of this 2-year-old notebook, here's a recent project by my colleague, digging very deep into the problem of tracking in football. Unlike this notebook, it uses recent models and `supervision` features.

While there's a little bit more info to pick through, I bet you'll find it both more performant and easier to use (that's what we've been working towards!).

Alternatively, if you're looking for a quick way to track objects, check out our docs: https://supervision.roboflow.com/latest/how_to/track_objects/

Best of luck!

**Comment by aamirali13** [comment]
Ok Thanks @LinasKo 
I'll definitely look into your suggested resource
