### ISSUE TITLE
Deploy bug

### ISSUE THREAD

**Issue by mikearney** [roboflow/notebooks#51]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

train-yolov8-object-detection-on-custom-dataset.ipynb

### Bug

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/4148169/214199439-fafe7a0d-b783-4a40-8cd6-c0a06224854d.png">

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-19-cec2a1551afa>](https://localhost:8080/#) in <module>
----> 1 project.version(dataset.version).deploy(model_type="yolov8", model_path=f"/content/runs/detect/train")

3 frames
[/usr/local/lib/python3.8/dist-packages/roboflow/core/version.py](https://localhost:8080/#) in deploy(self, model_type, model_path)
    311         # add logic to save torch state dict safely
    312         if model_type == "yolov8":
--> 313             model = torch.load(model_path + "weights/best.pt")
    314 
    315             class_names = []

[/usr/local/lib/python3.8/dist-packages/torch/serialization.py](https://localhost:8080/#) in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    769         pickle_load_args['encoding'] = 'utf-8'
    770 
--> 771     with _open_file_like(f, 'rb') as opened_file:
    772         if _is_zipfile(opened_file):
    773             # The zipfile reader is going to advance the current file position.

[/usr/local/lib/python3.8/dist-packages/torch/serialization.py](https://localhost:8080/#) in _open_file_like(name_or_buffer, mode)
    268 def _open_file_like(name_or_buffer, mode):
    269     if _is_path(name_or_buffer):
--> 270         return _open_file(name_or_buffer, mode)
    271     else:
    272         if 'w' in mode:

[/usr/local/lib/python3.8/dist-packages/torch/serialization.py](https://localhost:8080/#) in __init__(self, name, mode)
    249 class _open_file(_opener):
    250     def __init__(self, name, mode):
--> 251         super(_open_file, self).__init__(open(name, mode))
    252 
    253     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: '/content/runs/detect/trainweights/best.pt'
```

Colab

### Additional

Hope this is not another oversight from me, but I'm stuck :( 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mo-traor3-ai** [comment]
@mikearney All I'm seeing is that the path to your model weights isn't being found.
```
FileNotFoundError: [Errno 2] No such file or directory: '/content/runs/detect/trainweights/best.pt'
```

Did you run that cell before updating the path to `"{HOME}/runs/detect/train/"`, or after changing it from `"{HOME}/runs/detect/train"`

The only thing causing the error is missing a `/` in the path to your model weights:
* the error can't find this directory, `'/content/runs/detect/trainweights/best.pt'`, because its likely supposed to be this: `'/content/runs/detect/train/weights/best.pt'` (unless you changed your train folder to be called `trainweights`?
* Line 287 in `version.py` begins the definition of the deploy function: https://github.com/roboflow/roboflow-python/blob/main/roboflow/core/version.py#L287

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/89935638/214206632-5de1a842-b573-4648-9108-658eb0501605.png">

**Comment by Jacobsolawetz** [comment]
@mikearney I was thinking the same thing perhaps as @mo-traor3-ai

**Comment by SkalskiP** [comment]
@mikearney I also submitted a PR to `roboflow` pip package to make that `/` just optional.

**Comment by SkalskiP** [comment]
@mikearney please let me know if those tips solved your issue.

**Comment by mikearney** [comment]
Solved. Thank you
